<?php

/**
 * Implementation of hook_perm()
 */
function tw_password_mgmt_permission()
{
	return array
	(
		'Administer force password change' => array
		(
			'title' => t('Force changing of passwords'),
			'description' => t('Gives users the ability to force users to change their password.'),
		),
	);
}

/**
 * Implementation of hook_menu()
 */
function tw_password_mgmt_menu()
{
	$menu['admin/config/people/tw_password_mgmt'] = array
	(
		'title' => 'TRIPwire Password Management',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tw_password_mgmt_settings'),
		'access arguments' => array('Administer force password change'),
		'file' => 'tw_password_mgmt.pages.inc',
	);
	$menu['admin/config/people/tw_password_mgmt/emails'] = array
	(
		'title' => 'TRIPwire Password Management Email Settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tw_password_mgmt_email_settings'),
		'access arguments' => array('Administer force password change'),
		'file' => 'tw_password_mgmt.email.inc',
	);
	$menu['admin/config/people/tw_password_mgmt/unlock'] = array
	(
		'title' => 'TRIPwire Password Management Unlock User',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('tw_password_mgmt_unlock'),
		'access arguments' => array('Administer force password change'),
		'file' => 'tw_password_mgmt.unlock.inc',
	);
	return $menu;
}

/**
 * Implementation of hook_init()
 *
 * This function checks two things:
 * 1) Whether the user's account has been flagged to change their password
 * 2) Whether their password has expired
 * 
 * If either of the two conditions above returns true, they are redirected to the change password page
 */
function tw_password_mgmt_init()
{
	global $user;

	if(variable_get('tw_password_mgmt_module_enabled', TRUE))
	{
		// Get the url for the change password screen as set in on the settings page. This is because
		// users may have aliased the change password page, or used the chpwd module which moves the
		// change password screen to another page altogether
		$change_password_url = preg_replace('/!uid/', $user->uid, variable_get('tw_password_mgmt_change_password_url', 'user/!uid/edit'));

		// We should check for AJAX, but the request isn't. Sniffing headers isn't a
		// perfect method, but this header should be present much of the time.
		$ajax_request = !empty($_SERVER['HTTP_X_REQUESTED_WITH']) && !$_SERVER['HTTP_X_REQUESTED_WITH'] != 'XMLHttpRequest';

		/**
		 * Redirects should only happen if:
		 * - the user is logged in
		 * - not in an ajax callback
		 * - not on the change password page
		 * - not logging out
		 * - not requesting a new password
		 */
		if($user->uid && !$ajax_request && !in_array(current_path(), array($change_password_url, 'user/logout', drupal_get_path_alias('user/logout'), 'user/password', drupal_get_path_alias('user/password'), 'masquerade/unswitch')))
		{
			// T2OM-79: First checking for a user with account_state of expired.  This reflects step 7g in account processes
			$expiredtest = 0;
			$expiredtest = tw_password_mgmt_check_for_expired($user->uid);
			if ($expiredtest !== 0) {
				setcookie('my_message', t("Please contact the TRIPwire Help Desk at 1-866-987-9473 from 8 AM - 5 PM Eastern for assistance."), time() + (86400 * 30), "/");
				drupal_goto('/user/logout');
			}

			$redirect = FALSE;
			// Check whether testing is done on every page, or only on login
			if(variable_get('tw_password_mgmt_login_or_init', 0))
			{
				// Enter here when testing is done only on login
				// Pending users is a list of UIDs for all users who have logged in
				// and been flagged to change their password
				$pending_users = variable_get('tw_password_mgmt_pending_login_users', array());
				if(isset($pending_users[$user->uid]))
				{
					// The user is required to change their password.
					// Force a redirect to the password change page.
					$value = $pending_users[$user->uid]['value'];
					$destination = array();
					$redirect = TRUE;
				}
			}
			else
			{
				// Enter here when testing is done on every page.
				// Check to see if a password change is pending.
				$pending_change = tw_password_mgmt_check();
				if($pending_change)
				{
					// The user is required to change their password.
					// Force a redirect to the user password change page.
					$value = $pending_change;
					$destination = array('query' => array('destination' => $_GET['q'], 'reset' => 'force'));
					$redirect = TRUE;
				}
			}
			if($redirect)
			{
				// The user is redirected. A message needs to be set informing them of the reason
				// for being redirected to the password change page.
				//
				// When value is 1, the user has been forced to change their password by an administrator
				// If value is not 1, it is a timestamp indicating the time period after which their password
				// is set to expire.
				if($value == 1)
				{
					drupal_set_message(t('An administrator has required that you change your password. Please change your password to proceed.'), 'error', FALSE);
				}
				else
				{
					$time_period = tw_password_mgmt_get_text_date($value);
					drupal_set_message(t('This site requires that you change your password every !time_period. Please change your password to proceed.', array('!time_period' => $time_period)));
				}
				// Redirect the user to the change password page
				drupal_goto($change_password_url, $destination);
			}
		}
	}
}

function tw_password_mgmt_mail ($key, &$message, $params) {
  switch ($key) {
    case 'fourteendays':
      //Set headers etc
      $message['subject'] = t('TRIPwire Password Reset Warning (14 Days)');
	  $message['body'] = $params['emailbody'];
	  break;
	case 'sevendays':
      //Set headers etc
      $message['subject'] = t('TRIPwire Password Reset Warning (7 Days)');
	  $message['body'] = $params['emailbody'];
      break;
	case 'sixmonths':
      //Set headers etc
      $message['subject'] = t('TRIPwire Password Expired for Six Months');
	  $message['body'] = $params['emailbody'];
	  break;
	case 'locked':
      //Set headers etc
      $message['subject'] = t('TRIPwire Account Locked Notification (Expired Password)');
	  $message['body'] = $params['emailbody'];
      break;
  }
}

/**
 * Checks whether or not user has a pending password change
 */
function tw_password_mgmt_check()
{
	global $user;
	// If the user's account has been flagged, a redirect is required
	if(isset($user->tw_password_mgmt) && $user->tw_password_mgmt)
	{
		return 1;
	}
	// Only check to see if their password has expired if password expiry
	// is turned on in the module settings page.
	elseif(variable_get('tw_password_mgmt_expire_password', FALSE))
	{
		// The user's account has not been flagged. Check to see
		// if their password has expired according to the rules of the module.
		//
		// First thing is to check the time of their last password change,
		// and the time of their account creation
		$query = db_select('tw_password_mgmt_users', 'fpcu');
		$alias = $query->join('users', 'u', 'u.uid = fpcu.uid');
		$query
			->fields('fpcu', array('last_password_change'))
			->fields($alias, array('created'))
			->condition($alias . '.uid', $user->uid);
		$user_data = $query->execute()->fetchObject();

		// Get the time period after which their password should expire
		// according to the rules laid out in the module settings page. Only the
		// role with the highest priority is retrieved
		$query = db_select('tw_password_mgmt_expiry', 'fpce');
		$expiry = $query
			->fields('fpce', array('expiry'))
			->condition('fpce.rid', array_keys($user->roles), 'IN')
			->orderBy('fpce.weight')
			->range(0, 1)
			->addTag('tw_password_mgmt_expiry_check')
			->execute()
			->fetchField();

		//dpm("Password created on " . date('d-m-Y H:i:s', $user_data->last_password_change));
		//dpm("Password will expire on " . date('d-m-Y H:i:s', $user_data->last_password_change + $expiry));
		//dpm("Password warning will begin on " . date('d-m-Y H:i:s', strtotime('-10 days', $user_data->last_password_change + $expiry)));
		//dpm("Now is " . date('d-m-Y H:i:s', REQUEST_TIME));
		// Test to see if password will expire within 7 days
		if($expiry && ($user_data->last_password_change != '' && (REQUEST_TIME > (strtotime('-7 days', $user_data->last_password_change + $expiry))))) {
			if((REQUEST_TIME - $expiry) < $user_data->last_password_change) {
			  //dpm("within 7 days");
			  drupal_set_message('Your password will expire in less than 7 days.  Please consider changing it now by <a href="/user/' . $user->uid . '/edit?reset=seven">clicking here</a>.', 'warning', FALSE);		  
			}
		// Test to see if password will expire within 14 days
        } elseif($expiry && ($user_data->last_password_change != '' && (REQUEST_TIME > (strtotime('-14 days', $user_data->last_password_change + $expiry))))) {
			if((REQUEST_TIME - $expiry) < $user_data->last_password_change) {
			  //dpm("within 14 days");
			  drupal_set_message('Your password will expire in less than 14 days.  Please consider changing it now by <a href="/user/' . $user->uid . '/edit?reset=fourteen">clicking here</a>.', 'warning', FALSE);		  
			}
		}
        		
		// Test to see if their password has expired
		if($expiry && ($user_data->last_password_change != '' && (REQUEST_TIME - $expiry) > $user_data->last_password_change) || ($user_data->last_password_change == '' && (REQUEST_TIME - $expiry) > $user_data->created))
		{
			// Their password has expired, so their user account is flagged
			// and the expiration time period is returned, which will trigger the redirect
			// and be used to generate the message shown to the user
			$tid = taxonomy_get_term_by_name('Locked', 'account_states');
            $user->field_account_states['und'][0]['tid'] = array_shift($tid)->tid;
            user_save($user);
			$query = db_update('users')
				->fields(array('tw_password_mgmt' => 1))
				->condition('uid', $user->uid)
				->execute();
			return $expiry;
		}
	}
	return FALSE;
}

function tw_password_mgmt_check_for_expired($uid) {
	$user = user_load($uid);

	// T2OM-79: Auto logging out any user who has account state set to expired
    $expired = taxonomy_get_term_by_name('Expired', 'account_states');
    $expired = array_shift($expired);
	$accstate = array($expired->tid);
	
    if (in_array($user->field_account_states['und'][0]['tid'], $accstate)) {
		return $uid;
	} else {
		return 0;
	}
}

/**
 * Converts a time period of password expiry dates to the textual representation
 * of the number of years, months, days or hours that it represents
 */
function tw_password_mgmt_get_text_date($timestamp)
{
	$year = 60 * 60 * 24 * 365;
	if($timestamp % $year === 0)
	{
		$time_period = $timestamp / $year;
		$time_period = ($time_period > 1) ? $time_period . ' ' . t('years') : t('year');
	}
	else
	{
		$week = 60 * 60 * 24 * 7;
		if($timestamp % $week === 0)
		{
			$time_period = $timestamp / $week;
			$time_period = ($time_period > 1) ? $time_period . ' ' . t('weeks') : t('week');
		}
		else
		{
			$day = 60 * 60 * 24;
			if($timestamp % $day === 0)
			{
				$time_period = $timestamp / $day;
				$time_period = ($time_period > 1) ? $time_period . ' ' . t('days') : t('day');
			}
			else
			{
				$hour = 60 * 60;
				if($timestamp % $hour === 0)
				{
					$time_period = $timestamp / $hour;
					$time_period = ($time_period > 1) ? $time_period . ' ' . t('hours') : t('hour');
				}
			}
		}
	}
	return $time_period;
}

/**
 * Implementation of hook_user_login()
 */
function tw_password_mgmt_user_login(&$edit, $account)
{	
	// Only test if the user's password should be checked when
	// the site's settings require it on login and not on
	// every page load.
	if(variable_get('tw_password_mgmt_login_or_init', 0))
	{
		// Check to see if the user has a pending password change
		$pending_change = tw_password_mgmt_check();
		if($pending_change)
		{
			// The user has been required to change their password, so their 
			// password change data is added to the {variables} table.
			$pending_users = variable_get('tw_password_mgmt_pending_login_users', array());
			$pending_users[$account->uid] = array
			(
				// The current path is taken as a destination for the user so they can be
				// redirected back to it after changing their password
				'destination' => current_path(),
				'value' => $pending_change,
			);
			variable_set('tw_password_mgmt_pending_login_users', $pending_users);
		}
	}
}

/**
 * Implementation of hook_user_insert()
 */
function tw_password_mgmt_user_insert(&$edit, $account, $category)
{
	// This module requires that their is a row in the {tw_password_mgmt_users} table
	// for every user. This query adds that row to the database.
	$query = db_insert('tw_password_mgmt_users')
		->fields(array('uid' => $account->uid))
		->execute();

	// If the site settings require users to change their password on first time login,
	// the user's account is flagged to have the password changed.
	if(variable_get('tw_password_mgmt_first_time_login_password_change', 0))
	{
		$query = db_update('users')
			->fields(array('tw_password_mgmt' => 1))
			->condition('uid', $account->uid)
			->execute();
	}
	// Admins with the proper permissions can flag a user to change their password. 
	elseif(isset($edit['tw_password_mgmt']) && $edit['tw_password_mgmt'])
	{
		$query = db_update('users')
			->fields(array('tw_password_mgmt' => 1))
			->condition('uid', $account->uid)
			->execute();
		$forced_uids = variable_get('tw_password_mgmt_first_time_uids', array());
		$forced_uids[$account->uid] = $account->uid;
		variable_set('tw_password_mgmt_first_time_uids', $forced_uids);
	}
	unset($edit['tw_password_mgmt']);
}

/**
 * Implementation of hook_user_presave()
 */

 function tw_password_user_presave(&$edit, $account, $category) {
	global $user;
	// TRIP2-544: Moved this functionality from hook_user_update to hook_user_presave because when user changed their own password the user_save function was causing new password not to be saved 
	// This next conditional is entered when a user is changing their own password
	 $tid = taxonomy_get_term_by_name('Active', 'account_states');
	 $user->field_account_states['und'][0]['tid'] = array_shift($tid)->tid;
	 $user->tw_password_mgmt = '0';
	 user_save($user);
 }

/**
 * Implementation of hook_user_update()
 */
function tw_password_mgmt_user_update(&$edit, $account, $category)
{
	global $user;
	// If a user has changed their password, the time of their password change is
	// saved to the database.
	if($account->pass != $account->original->pass)
	{
		$query = db_update('tw_password_mgmt_users')
			->fields(array('last_password_change' => REQUEST_TIME))
			->condition('uid', $account->uid)
			->execute();

		// Also resetting the email notifications since the password reset kicks off a new date for when the password expires
		$query2 = db_update('tw_password_mgmt_emails')
			->fields(array('fourteen_day_email' => NULL))
			->condition('uid', $account->uid)
			->execute();

		$query3 = db_update('tw_password_mgmt_emails')
			->fields(array('seven_day_email' => NULL))
			->condition('uid', $account->uid)
			->execute();

		// Changing TW Account State back to Active if the user is already active. We do this if statement to avoid acting on a newly registered user
		$approved_term = taxonomy_get_term_by_name('Approved', 'user_status');
		$approved_term_id = array_shift($approved_term)->tid;
		if (isset($account->field_user_status)) {
			if ($account->field_user_status['und'][0]['tid'] == $approved_term_id) {
				$tid = taxonomy_get_term_by_name('Active', 'account_states');
				$tid_id = array_shift($tid)->tid;
				$active_query = db_update('field_data_field_account_states')
				->fields(array('field_account_states_tid' => $tid_id))
				->condition('entity_id', $account->uid)
				->execute();
			}
		}
	}
	// This next conditional is entered when a user is changing their own password
	if($account->tw_password_mgmt && $user->uid == $account->uid && isset($edit['pending_tw_password_mgmt']) && $edit['pending_tw_password_mgmt'])
	{
		// Remove the flag from the users account
		$query = db_update('users')
			->fields(array('tw_password_mgmt' => 0))
			->condition('uid', $user->uid)
			->execute();
		
		$forced_uids = variable_get('tw_password_mgmt_first_time_uids', array());
		if(isset($forced_uids[$account->uid]))
		{
			unset($forced_uids[$account->uid]);
			variable_set('tw_password_mgmt_first_time_uids', $forced_uids);
		}
		$pending_users = variable_get('tw_password_mgmt_pending_login_users', array());
		if(isset($pending_users[$account->uid]))
		{
			$destination = $pending_users[$account->uid]['destination'];
			unset($pending_users[$account->uid]);
			variable_set('tw_password_mgmt_pending_login_users', $pending_users);
			$_REQUEST['destination'] = $destination;
		}

		tw_user_history_write_record($edit, 'password', 'User changed their own password.', 'SKIP');
		
	}
	// An admin with the proper permissions is able to flag a user to change their password
	// on the user's account page. This next section setst that falg.
	if(isset($edit['tw_password_mgmt']) && $edit['tw_password_mgmt'])
	{
		$query = db_update('users')
			->fields(array('tw_password_mgmt' => 1))
			->condition('uid', $account->uid)
			->execute();
		// Flag the time of the forced password change for statistics sake.
		$query = db_update('tw_password_mgmt_users')
			->fields(array('last_force' => REQUEST_TIME))
			->condition('uid', $account->uid)
			->execute();
		unset($edit['tw_password_mgmt']);
	}
}

/**
 * Implementation of hook_user_delete()
 */
function tw_password_mgmt_user_delete($account)
{
	// When a user's account is deleted, their row is removed from the
	// {tw_password_mgmt_users} table in the database
	$query = db_delete('tw_password_mgmt_users')
		->condition('uid', $account->uid)
		->execute();
}

/**
 * This function is called after a user's account page is updated
 */
function tw_password_mgmt_validate_user($form, &$form_state)
{
	global $user;
	// Skipping this function for HSIN user role
	$hsinroles = array('HSIN', 'HSIN Pre-Authenticated');
	if (count(array_intersect($hsinroles, $user->roles)) > 0) {
		return;
	}
	// Check to see if the user's account has been flagged to change their password, and if so,
	// have they changed it?
	if(isset($form['#user']->tw_password_mgmt) && $form['#user']->tw_password_mgmt && $form['#user']->uid == $user->uid)
	{
		if($form_state['input']['pass']['pass1'] == '')
		{
			form_set_error('pass', t('You must choose a new password'));
		}
	}
	require_once DRUPAL_ROOT . '/' . variable_get('password_inc', 'includes/password.inc');
	// Check to see if the new password is different from the old password
	if(user_check_password($form_state['input']['pass']['pass1'], $form['#user']))
	{
		form_set_error('pass', t('You cannot use your current password. Please choose a different password.'));
	}
}

/**
 * Implementation of hook_form_alter()
 */
function tw_password_mgmt_form_alter(&$form, &$form_state, $form_id)
{
	// Alter the page that display's a list of roles on the site.
	if($form_id == 'user_admin_roles')
	{
		// Override the default theme and add one from this moulde in order to add a new
		// 'force password change' selection to the list of options
		$form['#theme'] = array('tw_password_mgmt_user_admin_roles_form');
		// the following submit function will add a new row to {tw_password_mgmt_roles}
		// add a new submit function for any new roles created.
		$form['add']['#submit'][] = 'tw_password_mgmt_add_role';
	}
	// Alter the role edit page for a single role
	elseif($form_id == 'user_admin_role')
	{
		// Set a message depending on whether pending password changes are checked on
		// every page, or only login
		if(variable_get('tw_password_mgmt_login_or_init', 0))
		{
			$description = t('Users who are not signed in will be required to change their password immediately upon login. Users who are currently signed in will be required to change their password upon their next page click, and after changing 
their password will be redirected back to the page they were attempting to access.');
		}
		else
		{
			$description = t('Users will be required to change their password upon their next login.');
		}
		$form['tw_password_mgmt'] = array
		(
			'#type' => 'checkbox',
			'#title' => t('Force users in this role to change their password'),
			'#description' => $description . '<br />' . t('Note: When you return to this page, this box will be unchecked. This is because this setting is a trigger, not a persistant state.'),
			'#weight' => -1,
		);
		$form['name']['#weight'] = -2;
		// Add a custom submit function that removes the role from the {tw_password_mgmt_roles} table
		$form['actions']['delete']['#submit'][] = 'tw_password_mgmt_delete_role';
		// Add a custom submit function that forces all users in the role to change their password
		$form['#submit'][] = 'tw_password_mgmt_edit_role';
	}
	// Alter the user profile form
	elseif($form_id == 'user_profile_form')
	{
		// Only need to make changes on the account tab.
		if($form['#user_category'] == 'account')
		{
			global $user;
			// Only alter the form if the user has the correct permission
			if(user_access('Administer force password change', $user))
			{
				// Find out where the password area lies, in case
				// a module has moved it from its default location
				if(isset($form['account']))
				{
					$use_form = &$form['account'];
				}
				else
				{
					$use_form = &$form;
				}
				// Set a weight on the name and email
				// fields to ensure they remain at the top
				$use_form['name']['#weight'] = -10;
				$use_form['mail']['#weight'] = -9;

				// Create a fieldset to contain all password information
				$use_form['password'] = array
				(
					'#type' => 'fieldset',
					'#title' => t('Password'),
					'#weight' => -1,
				);
				// Add the original password field to the fieldset
				$use_form['password']['pass'] = $use_form['pass'];
				if(isset($use_form['pass']))
				{
					unset($use_form['pass']);
				}

				// Get the correct message to show depending on the site settings
				if(variable_get('tw_password_mgmt_login_or_init', 0))
				{
					$description = t('If this box is checked, the user will be forced to change their password. If the user is signed in, they will be forced to change their password on their next page load. If they are not signed in, they 
will be forced to change their password the next time they log in.');
				}
				else
				{
					$description = t('If this box is checked, the user will be forced to change their password upon their next login.');
				}
				$use_form['password']['tw_password_mgmt'] = array
				(
					'#type' => 'checkbox',
					'#title' => t('Password Reset Required At Next Login'),
					'#access' => user_access('Administer force password change'),
					'#description' => $description . '<br />' . t('Note: This box will be unchecked each time the page is loaded, as it is a trigger, not a persistent state.'),
				);
				// Get the data regarding the users last password change and last force
				$force_password_data = db_query('SELECT last_password_change, last_force FROM {tw_password_mgmt_users} WHERE uid = :uid', array(':uid' => $form['#user']->uid))->fetchObject();
				if($force_password_data->last_force != '')
				{
					$last_force = format_date($force_password_data->last_force, 'small');
				}
				elseif(variable_get('tw_password_mgmt_first_time_login_password_change', FALSE) && $form['#user']->created > variable_get('tw_password_mgmt_installation_date', 0))
				{
					$last_force = t('Their first login');
				}
				else
				{
					$forced_uids = variable_get('tw_password_mgmt_first_login_change', array());
					if(count($forced_uids) && isset($forced_uids[$form['#user']->uid]))
					{
						$last_force = t('Their first login');
					}
					elseif($force_password_data->last_password_change != '')
					{
						$last_force = t('Their first login');
					}
					else
					{
						$last_force = t('Never');
					}
				}
				// TRIP2-500: Adding a check for when password will expire
				$last_change_query = db_select('tw_password_mgmt_users', 'fpcu');
				$alias = $last_change_query->join('users', 'u', 'u.uid = fpcu.uid');
				$last_change_query
					->fields('fpcu', array('last_password_change'))
					->fields($alias, array('created'))
					->condition($alias . '.uid', $form['#user']->uid);
				$user_data = $last_change_query->execute()->fetchObject();

				$expiry_query = db_select('tw_password_mgmt_expiry', 'fpce');
				$expiry = $expiry_query
					->fields('fpce', array('expiry'))
					->condition('fpce.rid', array_keys($form['#user']->roles), 'IN')
					->orderBy('fpce.weight')
					->range(0, 1)
					->addTag('tw_password_mgmt_expiry_check')
					->execute()
					->fetchField();
				//dpm("Password will expire on " . date('d-m-Y H:i:s', $user_data->last_password_change + $expiry));
				$variables = array
				(
					'pending_change' => ($form['#user']->tw_password_mgmt) ? t('Yes') : t('No'),
					'last_force' => $last_force,
					'last_change' => ($force_password_data->last_password_change != '') ? format_date($force_password_data->last_password_change, 'small') : t('Never'),
					'expire_date' => format_date($user_data->last_password_change + $expiry, 'small'),
				);
				// Display the user's password change stats for the administrator
				$use_form['password']['password_stats'] = array
				(
					'#markup' => theme('tw_password_mgmt_stats', $variables),
				);
			}

			$pass_reset = isset($_SESSION['pass_reset_' . $form['#user']->uid]) && isset($_GET['pass-reset-token']) && ($_GET['pass-reset-token'] == $_SESSION['pass_reset_' . $form['#user']->uid]);
			$protected_values = array();
			// The user may only change their own password without their current
			// password if they logged in via a one-time login link.
			if(!$pass_reset)
			{
				$protected_values['mail'] = $form['account']['mail']['#title'];
				$protected_values['pass'] = t('Password');
				$request_new = l(t('request a new password'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'))));
				$form['account']['current_pass']['#description'] = t('Enter your current password to change the %mail or %pass. If you do not know your current password, you can !request_new.', array('%mail' => $protected_values['mail'], '%pass' 
=> $protected_values['pass'], '!request_new' => $request_new));
			}

			// Set a flag that will be used in hook_update_user()
			$form['pending_tw_password_mgmt'] = array
			(
				'#type' => 'value',
				'#value' => $form['#user']->tw_password_mgmt,
			);
			// Add a custom validation function to check that the user has both filled in a password, and that it
			// has been changed from the previous password
			$form['#validate'][] = 'tw_password_mgmt_validate_user';
		}
	}
	elseif($form_id == 'user_register_form' && $GLOBALS['user']->uid != 0)
	{
		// Add the option to force the user to change their password on
		// first time login only if it is not turned on site-wide
		if(variable_get('tw_password_mgmt_first_login_change', 0))
		{
			// Get the location of the password field
			if ($form['account'])
			{
				$use_form = &$form['account'];
			}
			else
			{
				$use_form = &$form;
			}
			$use_form['name']['#weight'] = -10;
			$use_form['mail']['#weight'] = -9;
			$use_form['password']['#weight'] = -8;
			$use_form['password']['pass'] = $use_form['pass'];
			unset($use_form['pass']);
			$use_form['password']['tw_password_mgmt'] = array
			(
				'#type' => 'checkbox',
				'#title' => t('Force password change on first-time login'),
				'#description' => t('If this box is checked, the user will be forced to change their password on their first login.'),
				'#access' => user_access('Administer force password change'),
			);
		}
	}

	if ($form_id == 'user_pass_reset') {
		//$form['#submit'][] = 'tw_password_mgmt_clear_flood';
		array_unshift($form['#submit'], 'tw_password_mgmt_clear_flood');
	}
}

function tw_password_mgmt_clear_flood($form, &$form_state) {
	$account = db_query("SELECT * FROM {users} WHERE name = :name AND status = 1", array(
		':name' => $form_state['values']['name'],
	  	))->fetchObject();

	if ($account) {
		if (variable_get('user_failed_login_identifier_uid_only', FALSE)) {
		
			// Register flood events based on the uid only, so they apply for any
			// IP address. This is the most secure option.
			$identifier = $account->uid;
		} else {
		
			// The default identifier is a combination of uid and IP address. This
			// is less secure but more resistant to denial-of-service attacks that
			// could lock out all users with public user names.
			$identifier = $account->uid . '-' . ip_address();
		}
	}
	if (isset($identifier)) {
		
		// Clear past failures for this user so as not to block a user who might
		// log in and out more than once in an hour.
		flood_clear_event('failed_login_attempt_user', $identifier);
	  }
}

/**
 * Implementation of hook_theme()
 */
function tw_password_mgmt_theme()
{
	return array
	(
		'tw_password_mgmt_user_admin_roles_form' => array
		(
			'render element' =>'form',
			'file' => 'tw_password_mgmt.pages.inc',
		),
		'tw_password_mgmt_settings' => array
		(
			'render element' => 'form',
			'file' => 'tw_password_mgmt.pages.inc',
		),
		'tw_password_mgmt_expiry' => array
		(
			'render element' => 'form',
			'file' => 'tw_password_mgmt.pages.inc',
		),
		'tw_password_mgmt_list' => array
		(
			'arguments' => array
			(
				'last_change' => NULL,
				'pending_users_table' => NULL,
				'non_pending_users_table' => NULL,
				'tw_password_mgmt_form' => NULL,
				'back_button' => NULL,
			),
			'file' => 'tw_password_mgmt.pages.inc',
		),
		'tw_password_mgmt_stats' => array
		(
			'arguments' => array
			(
				'variables' => array
				(
					'pending_change' => NULL,
					'last_force' => NULL,
					'last_change' => NULL,
				),
			),
			'file' => 'tw_password_mgmt.pages.inc',
		),
	);
}

/**
 * This function is called after a new role has been added to the system.
 * It creates a new row in the {tw_password_mgmt_roles} table for the role that has been created
 */
function tw_password_mgmt_add_role($form, &$form_state)
{
	$rid = db_query('SELECT rid FROM {role} WHERE name = :name', array(':name' => $form_state['values']['name']))->fetchCol();
	$query = db_insert('tw_password_mgmt_roles')
		->fields(array('rid' => $rid[0]))
		->execute();
}

/**
 * Callback #submit function called on the role edit page when the user clicks the delete button.
 * This function removes the fole from the {tw_password_mgmt_roles} table.
 */
function tw_password_mgmt_delete_role($form, &$form_state)
{
	$query = db_delete('tw_password_mgmt_roles')
		->condition('rid', $form_state['values']['rid'])
		->execute();	
}

/**
 * Callback #submit function called on the role edit page when the user clicks the save button
 */
function tw_password_mgmt_edit_role($form, &$form_state)
{
	// Only flag user's accounts to be changed if the checkbox
	// was selected
	if($form_state['values']['tw_password_mgmt'])
	{
		// Get the UIDs for all users in the role
		$db_uids = db_query
		(
			'SELECT uid ' .
			'FROM {users_roles} ' .
			'WHERE rid = :rid',
			array(':rid' => $form_state['values']['rid'])
		);
		$uids = array();
		foreach($db_uids as $uid)
		{
			$uids[] = $uid->uid;
		}
		if(isset($uids[0]))
		{
			// flag the users accounts
			tw_password_mgmt_force_users($uids);
		}
		// Set the last force time for the role for statistics sake
		$query = db_update('tw_password_mgmt_roles')
			->fields(array('last_force' => REQUEST_TIME))
			->condition('rid', $form_state['values']['rid'])
			->execute();

		if(variable_get('tw_password_mgmt_login_or_init', 0))
		{
			$description = t('Users in this role will be required to immediately change their password');
		}
		else
		{
			$description = t('Users will be required to change their password upon their next login.');
		}
		drupal_set_message($description);
	}
}

/**
 * This function flags users accounts to change their passwords
 * It also logs the force time for statistics sake. If $uids is
 * an empty array, all users will have their stats updated
 */
function tw_password_mgmt_force_users($uids = array())
{
	$query = db_update('users')
		->fields(array('tw_password_mgmt' => 1));
	if(!empty($uids))
	{
		$query->condition('uid', $uids, 'IN');
	}
	$query->execute();
	$query = db_update('tw_password_mgmt_users')
		->fields(array('last_force' => REQUEST_TIME));
	if(!empty($uids))
	{
		$query->condition('uid', $uids, 'IN');
	}
	$query->execute();
}


function tw_password_mgmt_cron() {
	if (date('H', time()) == 13) {
		module_load_include('user_check.inc', 'tw_password_mgmt');
		watchdog('tw_password_mgmt', 'Running user password check script', array(), WATCHDOG_INFO, NULL);
		tw_password_mgmt_user_check();
	}
}

function tw_password_mgmt_views_data() {
	$data['tw_password_mgmt_emails']['table']['group'] = t('TripWIRE Password Managemnt');
  
	$data['tw_password_mgmt_emails']['table']['base'] = array(
	  'field' => 'uid',
	  'title' => t('TripWIRE Password Management'), 
	  'help' => t('TripWIRE Password Management of when passwords were reset and other things.'), 
	  'weight' => -10,
	);

	$data['tw_password_mgmt_emails']['table']['join'] = array(
		'node' => array(
		  'left_field' => 'uid', 
		  'field' => 'uid',
		),
	  );
	
	  $data['tw_password_mgmt_emails']['uid'] = array(
		'title' => t('UID'), 
		'help' => t('The user ID.'), 
		'field' => array(
		  'handler' => 'views_handler_field_numeric', 
		  'click sortable' => TRUE,
		), 
		'filter' => array(
		  'handler' => 'views_handler_filter_numeric',
		), 
		'sort' => array(
		  'handler' => 'views_handler_sort',
		),
	  );

	  $data['tw_password_mgmt_emails']['fourteen_day_email'] = array(
		'title' => t('Timestamp field'), 
		'help' => t('A Unix timestamp indicating when a 14 day warning email was sent.'), 
		'field' => array(
		  'handler' => 'views_handler_field_date', 
		  'click sortable' => TRUE,
		), 
		'sort' => array(
		  'handler' => 'views_handler_sort_date',
		), 
		'filter' => array(
		  'handler' => 'views_handler_filter_date',
		),
	  );


	  $data['tw_password_mgmt_emails']['seven_day_email'] = array(
		'title' => t('Timestamp field'), 
		'help' => t('A Unix timestamp indicating when a 7 day warning email was sent.'), 
		'field' => array(
		  'handler' => 'views_handler_field_date', 
		  'click sortable' => TRUE,
		), 
		'sort' => array(
		  'handler' => 'views_handler_sort_date',
		), 
		'filter' => array(
		  'handler' => 'views_handler_filter_date',
		),
	  );

	  return $data;
}

function tw_password_mgmt_custom_theme() {
	// get arguments
	$arg = explode('/', substr(request_uri(), strlen(base_path())));
	// match {wildcard}/path 
	// Using strpos as $arg[1] may end up having stuff like so ?order=title&sort=asc
	if (isset($arg[2]) && strpos($arg[2], 'reset=force') !== false) {
	  drupal_add_css(drupal_get_path('module', 'tw_password_mgmt') . '/css/tw_password_mgmt_hide.css');
	  return 'rubix_responsive_theme';
	}
}